Update zotero.py to unpack dicts to avoid operand type error
Reason for change: merging `self.url_params` and `url_params` throws a type error because of the bitwise operation with dictionaries (`dict_a | dict_b`) starting at v3.5.

e.g., 

```
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 167, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 460, in _retrieve_data
    merged_params = params | self.url_params
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
Error: Process completed with exit code 1.
```

Changed: merge dictionaries by unpacking them.

I checked if there would be any issues with creating a new dictionary instead of merging in place and didn't find anywhere the merged params were being set or used outside of line 472 where they are passed to `merge_params` to generate the `final_params`.

Cheers!